### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by log0530**
fix sql

### CODE REVIEW

**Comment by saltpool** [comment]
I notice in your updated install.sh you removed the retrieval of credentials and db from the conf file that is written, and used the root password directly with the database name.

Can you please let me know the point of this, as the sql import works fine how it is currently?

**Comment by log0530** [comment]
failed to import sql on Ubuntu22.04

**Comment by saltpool** [comment]
I have used the script many dozens of times without any error, can you provide any logs or screenshots? Did all packages install correctly?

Anyone else having the same issue?

**Comment by TheMaintainer** [comment]
Hi guys

  Is this the same issue you got 1? 

Performing the SQL import

Could not open required defaults file: /home/root/.my.cnf
Fatal error in defaults handling. Program aborted

**Comment by saltpool** [comment]
> Could not open required defaults file: /home/root/.my.cnf Fatal error in defaults handling. Program aborted

By your error it would appear that you are running this script under the root account, which you shouldn't be doing. Note it says /home/root.  The first step should be to create a non root account and give it sudo privileges and run it under that.

Let me know if this isn't what you're doing.

**Comment by TheMaintainer** [comment]
> > Could not open required defaults file: /home/root/.my.cnf Fatal error in defaults handling. Program aborted
> 
> By your error it would appear that you are running this script under the root account, which you shouldn't be doing. Note it says /home/root. The first step should be to create a non root account and give it sudo privileges and run it under that.
> 
> Let me know if this isn't what you're doing.

Hi 
yeah first it seems like the error if I run as root  or run the install.sh with sudo  that is correct 

but noticed that  the same error happens if I run install.sh using  " sh install.sh " 

but when I run the script with "bash install.sh " everything  works 100%

maybe you can  try it your self  and confirm it then you can add it to readme section 

thank you very much for this script .

**Comment by saltpool** [comment]
Yes, this script needs to be run using bash. Everything in this repo is designed to be used with the Udemy course that explains how to install and configure this customised Yiimp.  The course takes you through each step of installation (and configuration) and also explains that the script needs to be run using bash.

**Pull request closed without merging**
